/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajeroautomatico;

import cajeroautomatico.modelo.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class CajeroForm extends javax.swing.JPanel {
    private final DBConnection db = DBConnection.getInstance();
    private Cuenta cuenta;
    
    /**
     * Creates new form CajeroForm
     */
    public CajeroForm() {
        initComponents();
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
        this.textFieldNumeroCuenta.setText(this.cuenta.getNumero());
        this.textFieldNombrePropietario.setText(this.cuenta.getNombrePropietario());
        this.textFieldSaldo.setText(Double.toString(this.cuenta.getSaldo()));
    }
    
    public void limpiarFormulario() {
        this.textFieldCantidadDepositar.setText("");
        this.textFieldCantidadTransferir.setText("");
        this.textFieldCuentaTransferir.setText("");
        this.textFieldRetiro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldNumeroCuenta = new javax.swing.JTextField();
        textFieldNombrePropietario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldCantidadDepositar = new javax.swing.JTextField();
        buttonDepositar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldRetiro = new javax.swing.JTextField();
        buttonRetirar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textFieldCuentaTransferir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldCantidadTransferir = new javax.swing.JTextField();
        buttonTransferir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Cajero");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Número de Cuenta");

        textFieldNumeroCuenta.setEditable(false);

        textFieldNombrePropietario.setEditable(false);

        jLabel4.setText("Nombre Propietario");

        textFieldSaldo.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Saldo");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Depositar");

        jLabel6.setText("Ingrese la cantidad");

        buttonDepositar.setText("Depositar");
        buttonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Retirar");

        jLabel8.setText("Ingrese la cantidad");

        buttonRetirar.setText("Retirar");
        buttonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetirarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Transferir");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cuenta destino");

        jLabel11.setText("Ingrese la cantidad");

        buttonTransferir.setText("Transferir");
        buttonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNombrePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(textFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDepositar))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldCantidadTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldCuentaTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldNombrePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDepositar))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRetirar))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textFieldCuentaTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textFieldCantidadTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTransferir))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositarActionPerformed
        double cantidad;
        try {
            cantidad = Double.parseDouble(this.textFieldCantidadDepositar.getText());
        } catch (NumberFormatException | NullPointerException nfe) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        if (cantidad < 0) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        this.db.depositar(this.cuenta.getNumero(), cantidad);
        this.cuenta.depositar(cantidad);
        JOptionPane.showMessageDialog(null, "Cantidad depositada correctamente");
        this.textFieldSaldo.setText(Double.toString(this.cuenta.getSaldo()));
        this.textFieldCantidadDepositar.setText("");
    }//GEN-LAST:event_buttonDepositarActionPerformed

    private void buttonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetirarActionPerformed
        // TODO add your handling code here:
        double cantidad;
        try {
            cantidad = Double.parseDouble(this.textFieldRetiro.getText());
        } catch (NumberFormatException | NullPointerException nfe) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        if (cantidad < 0) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        if (cantidad > this.cuenta.getSaldo()) {
            JOptionPane.showMessageDialog(null, "La cantidad a retirar excede el saldo");
            return;
        }
        this.db.retirar(this.cuenta.getNumero(), cantidad);
        this.cuenta.retirar(cantidad);
        JOptionPane.showMessageDialog(null, "Retiro efectuado correctamente");
        this.textFieldSaldo.setText(Double.toString(this.cuenta.getSaldo()));
        this.textFieldRetiro.setText("");
    }//GEN-LAST:event_buttonRetirarActionPerformed

    private void buttonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferirActionPerformed
        // TODO add your handling code here:
        String cuentaDestino = this.textFieldCuentaTransferir.getText();
        if (this.cuenta.getNumero().equals(cuentaDestino) || !db.existe(cuentaDestino)) {
            JOptionPane.showMessageDialog(null, "Cuenta destino inválida");
            return;
        }
        double cantidad;
        try {
            cantidad = Double.parseDouble(this.textFieldCantidadTransferir.getText());
        } catch (NumberFormatException | NullPointerException nfe) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        if (cantidad < 0) {
            JOptionPane.showMessageDialog(null, "Cantidad inválida");
            return;
        }
        if (cantidad > this.cuenta.getSaldo()) {
            JOptionPane.showMessageDialog(null, "La cantidad a transferir excede el saldo");
            return;
        }
        this.db.transferir(this.cuenta.getNumero(), cuentaDestino, cantidad);
        JOptionPane.showMessageDialog(null, "Se realizó la transferencia exitosamente");
        this.cuenta.retirar(cantidad);
        this.textFieldSaldo.setText(Double.toString(this.cuenta.getSaldo()));
        this.textFieldCuentaTransferir.setText("");
        this.textFieldCantidadTransferir.setText("");
    }//GEN-LAST:event_buttonTransferirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDepositar;
    private javax.swing.JButton buttonRetirar;
    private javax.swing.JButton buttonTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldCantidadDepositar;
    private javax.swing.JTextField textFieldCantidadTransferir;
    private javax.swing.JTextField textFieldCuentaTransferir;
    private javax.swing.JTextField textFieldNombrePropietario;
    private javax.swing.JTextField textFieldNumeroCuenta;
    private javax.swing.JTextField textFieldRetiro;
    private javax.swing.JTextField textFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
